version: '3'

services:
  website:
    container_name: bside_nextjs
    image: bside/website:latest
    ports:
      - "3001:3000"
    env_file: .env
    extra_hosts:
      - "host.docker.internal:host-gateway"


volumes:
  data:
